add project
Ar4i23/movies-explorer-frontend pull request #1
Opened 2023-11-03 11:49 UTC by Ar4i23

2023-11-03 13:11 UTC, Savallera requested changes
# Резюме по работе:

Здравствуйте!
У Вас получилась хорошая работа для первого раза. Будет еще 3 итерации для того, чтобы над ней можно было еще поработать и она выгодно смотрелась в Вашем портфолио.
Вносите правки без спешки, следите за тем, что изменилось после внесения той или иной правки в элементе. Убедитесь перед отправкой, что все правки внесены. Если есть трудности - обращайтесь к наставнику и старшему студенту, они обязательно Вам помогут.

## Верстка и JSX

### Критерии, влияющие на работоспособность
- [ ] <!--12--> Все блоки и элементы из макета сверстаны. Размеры и расположение не отличаются от макета на более, чем на 30px на десктопной версии и на 10px на остальных размерах экрана, для которых подготовлен макет. Отличия в размерах не должны визуально противоречить макету и выбиваться из заложенной в макет сетки, в этом случае требуется более строгое соответствие размерам макета.

	**Главная**
	- 768/320 https://yadi.sk/d/miYtfS4TTgmiYw
	- 320 https://yadi.sk/d/cVnDaQp1UhHLGg

	**Авторизация**
	- 1280/768 https://yadi.sk/d/BpD5ArHsb7Ji4A - Вход такое же замечание

	**Профиль**
	- 1280 https://yadi.sk/d/I6Fq_kxCPIPYcg
	- 768 https://yadi.sk/d/8U81kE_xwBx_zA
	- 320 https://yadi.sk/d/dvZb9wYUiZKw8Q

	**Фильмы**
	- 768 https://yadi.sk/d/6XxhWfVeuz5SRQ
	- 320 https://yadi.sk/d/6XxhWfVeuz5SRQ

	**Меню**
	- 768 https://yadi.sk/d/6GVZt2yjb1CFtA
	- 320 https://yadi.sk/d/ldLFk2DXzN5ZNg

	**404**
	- 1280 https://yadi.sk/i/HAXL6BTsS95JZA
	- 768 https://yadi.sk/d/ZFbjvNKJNK-FdA
	- 320 https://yadi.sk/d/AJDXRuq_fyhfUg

- [x] <!--10.55--> Проект адаптирован под различные разрешения экрана. Горизонтальный скролл не возникает на разрешениях от 320 пикселей и больше. Нельзя скрывать полосу прокрутки свойством overflow: hidden.
- [x] <!--9.55--> Корректно работает навигация между страницами и ссылки на внешние ресурсы: ни одна ссылка не ведёт в пустоту или на якорь, внешние ссылки открываются в новой вкладке. На все страницы проекта можно попасть, а скрытые блоки можно отобразить.
- [ ] <!--5.55--> Именование классов сделаны по БЭМ.

	- forma - скорректируйте именование формы по-английски, использовать кирилические звуки нежелательно.
	- header__button-green - используйте сложный модификатор для описания отличных цветовых тем, header__button_theme_primary
	- header_place - аналогичное замечание по применению булевого модификатора, корректнее будет использовать сложный
	- header__button_active-color - здесь хорошо использовать булевый, активная ссылки или нет header__button_active

- [ ] <!--8.55--> Отзывчивая вёрстка, которая корректно тянется на всех промежуточных разрешениях.

	- https://yadi.sk/i/h2uxCQsSH1QqLA В любом месте где есть контент не следует делать фиксацию по высоте, т.к. контент может измениться и это не должно поломать отображение. Если блок содержит фоновое изображение и контент используйте минимальную высоту, Вам следует самостоятельно на примере найти и исправить все похожие случаи

- [ ] <!--3.38--> В коде используется семантическая разметка: применяются семантические теги, выбор элементов при вёрстке корректен (параграф должен быть параграфом, список — списком); структура DOM-дерева состоит не только из контейнеров div.

	- https://yadi.sk/d/ZH32AFhDFGc9Uw Профиль, https://yadi.sk/d/sBRYJBc9eWotMA Фильмы - Проект содержит ошибки валидации, воспользуйтесь [валидатором для проверки](https://validator.w3.org/#validate_by_input)
	- Каждый основной контент на странице следует обернуть main, все кроме header и footer (Профиль)
	- Кнопка меню, Стрелка для ссылки, Кнопка аккаунта - Хорошей практикой считается отображать декоративные изображения/иконки на псевдоклассах `:before` и `:after` https://habr.com/ru/post/154319/
	- filter - включите чекбокс в форму поиска (общий селектор для поля кнопки поиска и чекбокса будет form)
	- search__border-line и все аналогичные дек.линии - хорошо все декоративные линии описывать стилями не создавая отдельный пустой див в разметке.

- [ ] <!--3.38--> Для позиционирования элементов выбран верный подход, описанный корректным синтаксисом.

	- form__input-error, profile__input-error - Не стоит использовать абсолютное позиционирование для контента, тем самым вырезается текстовое содержимое из общего потока HTML. Такое поведение является нежелательным в большинстве случаев, особенно для элементов, содержащих динамический контент. При изменении контента - другие блоки не видят данные изменения и верстка может начать некорректно отображаться. В любой блок с контентом можно добавить в два три раза текста и он не должен сломаться.

- [x] <!--3.38--> Каркас макета реализован на Flex layout или Grid layout;
- [x] <!--3.38--> Инфраструктурные файлы проекта созданы через CRA.
- [ ] <!--3.38--> Работа модальных окон настроена.

	- https://yadi.sk/d/1ilpnIli5txNcw Обратите внимание на страницу UI в макете Figma. На странице профиля следует использовать логику по макету. Изначально данные не доступны к изменению, после нажатия на Кнопку Редактировать состояние полей меняется, также нижняя панель с кнопками меняет свой вид. Также есть состояния ошибки (это можно заложить в верстку).

- [x] Разметка портирована в JSX:
	- [x] <!--3.38--> разметка заключена в ( ), лишние пустые <div> для этого не используются;
	- [x] <!--3.38--> разметка вынесена в соответствующие ей компоненты.
- [ ] В проекте есть:
	- [x] <!--3.38--> директория images/ с картинками,
	- [x] <!--3.38--> директория components/ с JS и CSS-файлами компонентов,
	- [x] <!--3.38--> директория fonts/ со шрифтами.

### Хорошие практики
- [ ] <!--2.14--> Кнопки, инпуты и ссылки реализованы во всех состояниях, указанных в макете.

	- Обратите внимание, что у активной вкладки на странице с фильмами/сохраненными фильмами дизайн немного отличается, она имеет отличную толщину шрифта. В мобильном меню активная вкладка всегда подчеркнута. Это можно сделать с помощью простых БЭМ модификаторов.

- [x] <!--2.14--> В макете есть одинаковые элементы. Для их оформления должен быть переиспользован один компонент.
- [x] <!--2.14--> Шрифты подключены через @font-face.
- [ ] <!--2.14--> Иконки экспортированы в формате SVG.

	- account-button.svg - скачайте только вектор, контент добавьте в разметку, а форму кнопки хорошо стилизовать
	- search-btn.svg - аналогичное замечание

- [x] <!--2.14--> Элементы формы должны выделяться, когда на них установлен фокус. Состояние фокуса, а также outline стилизованы в соответствии с макетом или на своё усмотрение.
- [ ] <!--2.14--> У формы должны быть заданы плейсхолдеры, валидированы обязательные поля.

	- Для тегов `<form>` следует заполнить атрибут name

- [x] <!--2.14--> reset.css запрещен.

### Рекомендации
- [ ] <!--1.68--> Для каждого шрифта указаны альтернативные варианты из системных шрифтов.

	- https://yadi.sk/d/pUY3Ructf4AT5Q один момент скорректировать нужно

- [ ] <!--1.67--> Для изображений задан атрибут alt с подходящий значением.

	- `<img alt="" className="film__image" />` - Атрибут `alt` не только обязательный с точки зрения валидности. Его нужно правильно заполнять, чтобы повышать уровень доступности вашего интерфейса. Руководство по `alt-text` от слабовидящего веб-разработчика (тут)[https://habr.com/ru/post/341810/]

- [ ] <!--1.67--> Растровые и векторные изображения оптимизированы;

	- landing-logo.svg - скачайте в формате png

## Количество баллов: 52

## Доп. Комментарии:
	- <html lang="en"> - язык проекта русский
	- Лишние(не используемые) шрифты следует удалить из проекта / Лишние подключения @font-face так же следует удалить
	- techs__list-item - хорошо бы удалить ховер эффект, т.к. это не интерактивные элементы, с ними нельзя взяимодействовать.

2023-11-04 16:19 UTC, Savallera requested changes
# Резюме по работе:

Здравствуйте!
Готово второе ревью на Ваш проект. Хорошая работа, много пунктов засчитано. 
Баллов пока недостаточно, для того, чтобы его принять, зато есть возможность улучшить работу и получить максимальный балл. Уверена у Вас все получится!

## Верстка и JSX

### Критерии, влияющие на работоспособность
- [x] <!--12--> Все блоки и элементы из макета сверстаны. Размеры и расположение не отличаются от макета на более, чем на 30px на десктопной версии и на 10px на остальных размерах экрана, для которых подготовлен макет. Отличия в размерах не должны визуально противоречить макету и выбиваться из заложенной в макет сетки, в этом случае требуется более строгое соответствие размерам макета.
- [x] <!--10.55--> Проект адаптирован под различные разрешения экрана. Горизонтальный скролл не возникает на разрешениях от 320 пикселей и больше. Нельзя скрывать полосу прокрутки свойством overflow: hidden.
- [x] <!--9.55--> Корректно работает навигация между страницами и ссылки на внешние ресурсы: ни одна ссылка не ведёт в пустоту или на якорь, внешние ссылки открываются в новой вкладке. На все страницы проекта можно попасть, а скрытые блоки можно отобразить.
- [x] <!--5.55--> Именование классов сделаны по БЭМ.
- [ ] <!--8.55--> Отзывчивая вёрстка, которая корректно тянется на всех промежуточных разрешениях.

	- https://yadi.sk/i/h2uxCQsSH1QqLA В любом месте где есть контент не следует делать фиксацию по высоте, т.к. контент может измениться и это не должно поломать отображение. Если блок содержит фоновое изображение и контент используйте минимальную высоту, Вам следует самостоятельно на примере найти и исправить все похожие случаи

- [ ] <!--3.38--> В коде используется семантическая разметка: применяются семантические теги, выбор элементов при вёрстке корректен (параграф должен быть параграфом, список — списком); структура DOM-дерева состоит не только из контейнеров div.

	- https://yadi.sk/d/bBMFp1mYrx8FYQ Фильмы - Сохраняется ошибка валидации - у селектора img должен быть обязательно описан атрибут src, воспользуйтесь [валидатором для проверки](https://validator.w3.org/#validate_by_input)
	- profile - Каждый основной контент на странице следует обернуть main, все кроме header и footer
	- Кнопка меню, Стрелка для ссылки, Кнопка аккаунта - Хорошей практикой считается отображать декоративные изображения/иконки на псевдоклассах `:before` и `:after` https://habr.com/ru/post/154319/
	- https://yadi.sk/d/T3kGw8DIb8InWQ filter - включите чекбокс в форму поиска (общий селектор для поля кнопки поиска и чекбокса будет form)
	- search__border-line и все аналогичные дек.линии - хорошо все декоративные линии описывать стилями не создавая отдельный пустой див в разметке.

- [ ] <!--3.38--> Для позиционирования элементов выбран верный подход, описанный корректным синтаксисом.

	- form__input-error, profile__input-error - Не стоит использовать абсолютное позиционирование для контента, тем самым вырезается текстовое содержимое из общего потока HTML. Такое поведение является нежелательным в большинстве случаев, особенно для элементов, содержащих динамический контент. При изменении контента - другие блоки не видят данные изменения и верстка может начать некорректно отображаться. В любой блок с контентом можно добавить в два три раза текста и он не должен сломаться.

- [x] <!--3.38--> Каркас макета реализован на Flex layout или Grid layout;
- [x] <!--3.38--> Инфраструктурные файлы проекта созданы через CRA.
- [ ] <!--3.38--> Работа модальных окон настроена.

	- https://yadi.sk/d/1ilpnIli5txNcw Обратите внимание на страницу UI в макете Figma. На странице профиля следует использовать логику по макету. Изначально данные не доступны к изменению, после нажатия на Кнопку Редактировать состояние полей меняется, также нижняя панель с кнопками меняет свой вид. Также есть состояния ошибки (это можно заложить в верстку).

- [x] Разметка портирована в JSX:
	- [x] <!--3.38--> разметка заключена в ( ), лишние пустые <div> для этого не используются;
	- [x] <!--3.38--> разметка вынесена в соответствующие ей компоненты.
- [ ] В проекте есть:
	- [x] <!--3.38--> директория images/ с картинками,
	- [x] <!--3.38--> директория components/ с JS и CSS-файлами компонентов,
	- [x] <!--3.38--> директория fonts/ со шрифтами.

### Хорошие практики
- [ ] <!--2.14--> Кнопки, инпуты и ссылки реализованы во всех состояниях, указанных в макете.

	- Обратите внимание, что у активной вкладки на странице с фильмами/сохраненными фильмами дизайн немного отличается, она имеет отличную толщину шрифта. В мобильном меню активная вкладка всегда подчеркнута. Это можно сделать с помощью простых БЭМ модификаторов.

- [x] <!--2.14--> В макете есть одинаковые элементы. Для их оформления должен быть переиспользован один компонент.
- [x] <!--2.14--> Шрифты подключены через @font-face.
- [ ] <!--2.14--> Иконки экспортированы в формате SVG.

	- account-button.svg - скачайте только вектор, контент добавьте в разметку, а форму кнопки хорошо стилизовать
	- search-btn.svg - аналогичное замечание

- [x] <!--2.14--> Элементы формы должны выделяться, когда на них установлен фокус. Состояние фокуса, а также outline стилизованы в соответствии с макетом или на своё усмотрение.
- [x] <!--2.14--> У формы должны быть заданы плейсхолдеры, валидированы обязательные поля.
- [x] <!--2.14--> reset.css запрещен.

### Рекомендации
- [x] <!--1.68--> Для каждого шрифта указаны альтернативные варианты из системных шрифтов.
- [ ] <!--1.67--> Для изображений задан атрибут alt с подходящий значением.

	- `<img alt="" className="film__image" />` - Атрибут `alt` не только обязательный с точки зрения валидности. Его нужно правильно заполнять, чтобы повышать уровень доступности вашего интерфейса. Руководство по `alt-text` от слабовидящего веб-разработчика (тут)[https://habr.com/ru/post/341810/]

- [x] <!--1.67--> Растровые и векторные изображения оптимизированы;

## Количество баллов: 75

## Доп. Комментарии:
	- Лишние(не используемые) шрифты следует удалить из проекта / Лишние подключения @font-face так же следует удалить
	- techs__list-item - хорошо бы удалить ховер эффект, т.к. это не интерактивные элементы, с ними нельзя взаимодействовать.
	- Хорошо бы удалить неиспользуемые изображения из папки images

2023-11-05 14:07 UTC, Ar4i23 commented
Не совсем понял про наполнение карточки контентом , у меня все работает прикладываю скрин , но все таки я поставил карточке мин. высоту .
![photo_2023-11-05 5 06 52 PM](https://github.com/Ar4i23/movies-explorer-frontend/assets/112895102/dc26f931-80b4-47e8-9bf4-e6feeb35d6f9)

2023-11-06 07:25 UTC, Savallera commented
> Не совсем понял про наполнение карточки контентом , у меня все работает прикладываю скрин , но все таки я поставил карточке мин. высоту . ![photo_2023-11-05 5 06 52 PM](https://user-images.githubusercontent.com/112895102/280532003-dc26f931-80b4-47e8-9bf4-e6feeb35d6f9.jpeg)

- Здравствуйте, Вы фиксируете высоту карточки фильма, https://yadi.sk/d/orpW4gp0iSyo-Q, из-за этого если заголовок будет иметь длинное название, то он будет выпадать из блока. Чтобы решить эту проблему, используйте таким набором свойств в CSS как:

```
text-overflow: ellipsis;
white-space: nowrap;
overflow: hidden;
max-width: {значение по макету}

```

2023-11-06 07:36 UTC, Savallera requested changes
# Резюме по работе:

Здравствуйте!
В текущей итерации не было засчитано дополнительных пунктов по чек-листу. Я немного расширила комментарии, если они вдруг были не совсем понятны. Чтобы принять работу нужно мин. 5 баллов. Уверена у Вас все получится!

## Верстка и JSX

### Критерии, влияющие на работоспособность
- [x] <!--12--> Все блоки и элементы из макета сверстаны. Размеры и расположение не отличаются от макета на более, чем на 30px на десктопной версии и на 10px на остальных размерах экрана, для которых подготовлен макет. Отличия в размерах не должны визуально противоречить макету и выбиваться из заложенной в макет сетки, в этом случае требуется более строгое соответствие размерам макета.
- [x] <!--10.55--> Проект адаптирован под различные разрешения экрана. Горизонтальный скролл не возникает на разрешениях от 320 пикселей и больше. Нельзя скрывать полосу прокрутки свойством overflow: hidden.
- [x] <!--9.55--> Корректно работает навигация между страницами и ссылки на внешние ресурсы: ни одна ссылка не ведёт в пустоту или на якорь, внешние ссылки открываются в новой вкладке. На все страницы проекта можно попасть, а скрытые блоки можно отобразить.
- [x] <!--5.55--> Именование классов сделаны по БЭМ.
- [ ] <!--8.55--> Отзывчивая вёрстка, которая корректно тянется на всех промежуточных разрешениях.

	- https://yadi.sk/d/orpW4gp0iSyo-Q Вы фиксируете высоту карточки, из-за этого если заголовок будет иметь длинное название, то он будет выпадать из блока. Чтобы решить эту проблему, используйте таким набором свойств в CSS как:

		```
			text-overflow: ellipsis;
			white-space: nowrap;
			overflow: hidden;
			max-width: {значение по макету}

		```

- [ ] <!--3.38--> В коде используется семантическая разметка: применяются семантические теги, выбор элементов при вёрстке корректен (параграф должен быть параграфом, список — списком); структура DOM-дерева состоит не только из контейнеров div.

	- https://yadi.sk/d/epA_xRgVQIy4lw profile - Каждый основной контент на странице следует обернуть main, все кроме header и footer
	- https://yadi.sk/d/1AIY6Pj-GAcgmA чекбокс относится к форме с поиском, неоправдано его оформлять отдельным селектором form, Вы можете использовать fieldset для разделения групп общей формы.

	- Можно лучше
	- Кнопка меню, Стрелка для ссылки, Кнопка аккаунта - Хорошей практикой считается отображать декоративные изображения/иконки на псевдоклассах `:before` и `:after` https://habr.com/ru/post/154319/
	- search__border-line и все аналогичные дек.линии - хорошо все декоративные линии описывать стилями не создавая отдельный пустой див в разметке.

- [ ] <!--3.38--> Для позиционирования элементов выбран верный подход, описанный корректным синтаксисом.

	- https://yadi.sk/d/7Z2FtKzHEeuMVw - при изменении текста ошибки он будет наезжать на сл.селектор - form__input-error, profile__input-error - Не стоит использовать абсолютное позиционирование для контента, тем самым вырезается текстовое содержимое из общего потока HTML. Такое поведение является нежелательным в большинстве случаев, особенно для элементов, содержащих динамический контент. При изменении контента - другие блоки не видят данные изменения и верстка может начать некорректно отображаться. В любой блок с контентом можно добавить в два три раза текста и он не должен сломаться.

- [x] <!--3.38--> Каркас макета реализован на Flex layout или Grid layout;
- [x] <!--3.38--> Инфраструктурные файлы проекта созданы через CRA.
- [ ] <!--3.38--> Работа модальных окон настроена.

	- Здесь следует заложить верстку по макету (Кнопка Сохранить с ошибкой - появляются при нажатии на Редактировать) - https://yadi.sk/d/1ilpnIli5txNcw Обратите внимание на страницу UI в макете Figma. На странице профиля следует использовать логику по макету. Изначально данные не доступны к изменению, после нажатия на Кнопку Редактировать состояние полей меняется, также нижняя панель с кнопками меняет свой вид. Также есть состояния ошибки (это можно заложить в верстку).

- [x] Разметка портирована в JSX:
	- [x] <!--3.38--> разметка заключена в ( ), лишние пустые <div> для этого не используются;
	- [x] <!--3.38--> разметка вынесена в соответствующие ей компоненты.
- [ ] В проекте есть:
	- [x] <!--3.38--> директория images/ с картинками,
	- [x] <!--3.38--> директория components/ с JS и CSS-файлами компонентов,
	- [x] <!--3.38--> директория fonts/ со шрифтами.

### Хорошие практики
- [ ] <!--2.14--> Кнопки, инпуты и ссылки реализованы во всех состояниях, указанных в макете.

	- Здесь необходимо добавить класс активной ссылки, где ей будет изменена толщина по макету (500), в мобильном меню нижнее подчеркивание. Обратите внимание, что у активной вкладки на странице с фильмами/сохраненными фильмами дизайн немного отличается, она имеет отличную толщину шрифта. В мобильном меню активная вкладка всегда подчеркнута. Это можно сделать с помощью простых БЭМ модификаторов.

- [x] <!--2.14--> В макете есть одинаковые элементы. Для их оформления должен быть переиспользован один компонент.
- [x] <!--2.14--> Шрифты подключены через @font-face.
- [ ] <!--2.14--> Иконки экспортированы в формате SVG.

	- account-button.svg - скачайте только вектор, контент добавьте в разметку, а форму кнопки хорошо стилизовать
	- search-btn.svg - аналогичное замечание

- [x] <!--2.14--> Элементы формы должны выделяться, когда на них установлен фокус. Состояние фокуса, а также outline стилизованы в соответствии с макетом или на своё усмотрение.
- [x] <!--2.14--> У формы должны быть заданы плейсхолдеры, валидированы обязательные поля.
- [x] <!--2.14--> reset.css запрещен.

### Рекомендации
- [x] <!--1.68--> Для каждого шрифта указаны альтернативные варианты из системных шрифтов.
- [ ] <!--1.67--> Для изображений задан атрибут alt с подходящий значением.

	- `<img alt="" className="film__image" />` - Атрибут `alt` не только обязательный с точки зрения валидности. Его нужно правильно заполнять, чтобы повышать уровень доступности вашего интерфейса. Руководство по `alt-text` от слабовидящего веб-разработчика (тут)[https://habr.com/ru/post/341810/]

- [x] <!--1.67--> Растровые и векторные изображения оптимизированы;

## Количество баллов: 75

## Доп. Комментарии:
	- Лишние(не используемые) шрифты следует удалить из проекта / Лишние подключения @font-face так же следует удалить
	- Хорошо бы удалить неиспользуемые изображения из папки images

2023-11-07 05:34 UTC, Savallera approved these changes
# Резюме по работе:

Здравствуйте!
У Вас получилась отличная работа. Поздравляю Ваш проект принят, желаю Вам дальнейших успехов во всех начинаниях!

## Верстка и JSX

### Критерии, влияющие на работоспособность
- [x] <!--12--> Все блоки и элементы из макета сверстаны. Размеры и расположение не отличаются от макета на более, чем на 30px на десктопной версии и на 10px на остальных размерах экрана, для которых подготовлен макет. Отличия в размерах не должны визуально противоречить макету и выбиваться из заложенной в макет сетки, в этом случае требуется более строгое соответствие размерам макета.
- [x] <!--10.55--> Проект адаптирован под различные разрешения экрана. Горизонтальный скролл не возникает на разрешениях от 320 пикселей и больше. Нельзя скрывать полосу прокрутки свойством overflow: hidden.
- [x] <!--9.55--> Корректно работает навигация между страницами и ссылки на внешние ресурсы: ни одна ссылка не ведёт в пустоту или на якорь, внешние ссылки открываются в новой вкладке. На все страницы проекта можно попасть, а скрытые блоки можно отобразить.
- [x] <!--5.55--> Именование классов сделаны по БЭМ.
- [x] <!--8.55--> Отзывчивая вёрстка, которая корректно тянется на всех промежуточных разрешениях.
- [x] <!--3.38--> В коде используется семантическая разметка: применяются семантические теги, выбор элементов при вёрстке корректен (параграф должен быть параграфом, список — списком); структура DOM-дерева состоит не только из контейнеров div.
- [x] <!--3.38--> Для позиционирования элементов выбран верный подход, описанный корректным синтаксисом.
- [x] <!--3.38--> Каркас макета реализован на Flex layout или Grid layout;
- [x] <!--3.38--> Инфраструктурные файлы проекта созданы через CRA.
- [ ] <!--3.38--> Работа модальных окон настроена.

	- Здесь следует заложить верстку по макету (Кнопка Сохранить с ошибкой - появляются при нажатии на Редактировать) - https://yadi.sk/d/1ilpnIli5txNcw Обратите внимание на страницу UI в макете Figma. На странице профиля следует использовать логику по макету. Изначально данные не доступны к изменению, после нажатия на Кнопку Редактировать состояние полей меняется, также нижняя панель с кнопками меняет свой вид. Также есть состояния ошибки (это можно заложить в верстку).

- [x] Разметка портирована в JSX:
	- [x] <!--3.38--> разметка заключена в ( ), лишние пустые <div> для этого не используются;
	- [x] <!--3.38--> разметка вынесена в соответствующие ей компоненты.
- [ ] В проекте есть:
	- [x] <!--3.38--> директория images/ с картинками,
	- [x] <!--3.38--> директория components/ с JS и CSS-файлами компонентов,
	- [x] <!--3.38--> директория fonts/ со шрифтами.

### Хорошие практики
- [ ] <!--2.14--> Кнопки, инпуты и ссылки реализованы во всех состояниях, указанных в макете.

	- Здесь необходимо добавить класс активной ссылки, где ей будет изменена толщина по макету (500), в мобильном меню нижнее подчеркивание. Обратите внимание, что у активной вкладки на странице с фильмами/сохраненными фильмами дизайн немного отличается, она имеет отличную толщину шрифта. В мобильном меню активная вкладка всегда подчеркнута. Это можно сделать с помощью простых БЭМ модификаторов.

- [x] <!--2.14--> В макете есть одинаковые элементы. Для их оформления должен быть переиспользован один компонент.
- [x] <!--2.14--> Шрифты подключены через @font-face.
- [ ] <!--2.14--> Иконки экспортированы в формате SVG.

	- account-button.svg - скачайте только вектор, контент добавьте в разметку, а форму кнопки хорошо стилизовать
	- search-btn.svg - аналогичное замечание

- [x] <!--2.14--> Элементы формы должны выделяться, когда на них установлен фокус. Состояние фокуса, а также outline стилизованы в соответствии с макетом или на своё усмотрение.
- [x] <!--2.14--> У формы должны быть заданы плейсхолдеры, валидированы обязательные поля.
- [x] <!--2.14--> reset.css запрещен.

### Рекомендации
- [x] <!--1.68--> Для каждого шрифта указаны альтернативные варианты из системных шрифтов.
- [x] <!--1.67--> Для изображений задан атрибут alt с подходящий значением.
- [x] <!--1.67--> Растровые и векторные изображения оптимизированы;

## Количество баллов: 92

2023-11-10 10:33 UTC, merged